# Use the PHP 8.3 runtime
runtime: php83

# Default entry point — serve login.php as your homepage
entrypoint: serve login.php

handlers:
  # Handle all PHP files (so signup.php, topicselection.php, etc. work)
  - url: /(.+\.php)$
    script: auto

  # Serve static assets (CSS, JS, images, etc.)
  - url: /(.+\.(gif|png|jpg|jpeg|css|js|ico|woff|woff2|ttf|svg))$
    static_files: \1
    upload: .+\.(gif|png|jpg|jpeg|css|js|ico|woff|woff2|ttf|svg)$

  # Default route — if no specific file is given, use login.php
  - url: /
    script: login.php