runtime: php83

entrypoint: serve sportarticleslist.php

handlers:
  # Route all PHP files
  - url: /(.*\.php)
    script: \1

  # Serve static assets (CSS, JS, images)
  - url: /(.+\.(gif|png|jpg|css|js|ico))
    static_files: \1
    upload: .+\.(gif|png|jpg|css|js|ico)

  # Default route (send all other traffic to login.php)
  - url: /.*
    script: login.php
